version: '3.12'

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/todo
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000